spring:
  h2:
    console:
      enabled: true
      path: '/console'
  datasource:
    url: 'jdbc:h2:file:/home/slawomir/IdeaProjects/Spring_shop/spring_shop_db'

  jpa:
    hibernate:
      ddl-auto:  update
    open-in-view: false
  flyway:
    baseline-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include: '*'




