spring:
  h2:
    console:
      enabled: true
      path: '/console'
  datasource:
    url: 'jdbc:h2:file:/home/slawomir/IdeaProjects/Spring_shop/spring_shop_db'

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-on-migrate: true


